### ISSUE TITLE
version of tailwind should be controllable ?

### ISSUE THREAD

**Issue by gedw99** [paganotoni/tailo#1]
I am using this with different projects, and I like to build idempotent systems.

when the setup is run on a project for a full lifecycle, I cant stick to 1 version and am currently exposed to shifting versions of tailwind. 

So, maybe the solution is to expose a Version, that matches versions available from tailwind.
The developer can then stick to a version and decide when he she wants to upgrade, just like we do with golang modules. 

Different devs use different ways of passing in the version they want, such as .env, etc .  I am not sure what is best yet.

The obvious place in code is here: https://github.com/paganotoni/tailo/blob/main/options.go

Here is the code point where we could control the version used: https://github.com/paganotoni/tailo/blob/main/setup.go#L42

Would appreciate feedback on this.

**Comment by paganotoni** [comment]
This is a good good point @gedw99.

**Comment by paganotoni** [comment]
We can allow flags or arguments on the setup command.

https://github.com/paganotoni/tailo/blob/main/cmd/setup/main.go#L6

Then based on that shift the url we use to pull the Tailwind binary.

**Comment by paganotoni** [comment]
@gedw99 this is covered in v1.0.8. I added an example in the README. please lets me know how it works for you. Regards!
